name: "Build, lint, and test"
on: [pull_request, push]
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  test:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start emulator
        run: scripts/start_emulator.sh
      - name: Evaluate ktlint
        run: ./gradlew ktlintCheck
      - name: Run screenshot tests tests
        run: ./gradlew debugExecuteScreenshotTests


